"""`python -m soul_buddy.api --port <p> --token <t> [--static-dir <dir>]`.

Electron spawns this. The token is generated by the shell and passed here so it
never has to travel over stdout (A09: only `SOULBUDDY_READY` is printed).
"""
from __future__ import annotations

import argparse
import os

import uvicorn

from ..logging_setup import setup_logging
from .main import create_app


def main() -> None:
    parser = argparse.ArgumentParser(prog="soul_buddy.api")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--token", type=str, default="")
    parser.add_argument("--static-dir", type=str, default="")
    args = parser.parse_args()

    # Propagate the shell-owned token to the lifespan Runtime via env (read once
    # at startup). Not logged, not in stdout.
    if args.token:
        os.environ["SOUL_BOOTSTRAP_TOKEN"] = args.token

    # File logging *before* uvicorn.run so every line (incl. uvicorn's own
    # startup banner and any crash during app creation) lands in sidecar.log.
    setup_logging()

    static_dir = args.static_dir or None
    app = create_app(static_dir=static_dir)
    # log_config=None → use our setup_logging() (propagate=True on uvicorn.error/
    # .access ensures every line flows through the root logger and lands in the
    # rotating sidecar.log). No uvicorn-specific formatters, no colored prefixes.
    uvicorn.run(app, host="127.0.0.1", port=args.port, workers=1,
                log_level="info", log_config=None)


if __name__ == "__main__":
    main()
