"""Anchor slugify for the docs site — keeps CJK characters.

Why this exists
---------------
Python-Markdown's built-in slugify strips every non-ASCII character, so

    ## 1. 什么是 AI Agent

produced the anchor ``1-ai-agent`` — the Chinese was silently dropped. Any
hand-written link to ``#1-什么是-ai-agent`` therefore failed, and the reader
landed back at the top of the page.

This implementation follows the GitHub convention, which is what the guide's
tables of contents were written against:

  1. NFC-normalise, strip, lowercase (casefold)
  2. full-width / CJK punctuation -> removed (``（`` ``）`` ``：`` ``、`` ...)
  3. every other non-word character (whitespace, ``.`` ``/`` ``+`` ...) -> ``-``
  4. runs of ``-`` collapsed to one; leading / trailing ``-`` stripped

Examples
--------
    "1. 什么是 AI Agent"                     -> "1-什么是-ai-agent"
    "3. Agent 的核心组成"                    -> "3-agent-的核心组成"
    "第一部分：工作区内四个项目分析"           -> "第一部分工作区内四个项目分析"
    "4. LATS（Language Agent Tree Search）"  -> "4-latslanguage-agent-tree-search"
    "2. Tool Use / Tool Calling"            -> "2-tool-use-tool-calling"

Registered from ``mkdocs.yml``:
    toc:
      slugify: !!python/name:docs._slugify.slugify

Note: a handful of anchors inside ``docs/knowledge/ai-agent-interview-guide/``
were generated by a different tool and do not match any consistent rule
(``#2-tool-use--tool-calling`` uses a double dash, ``#8-综合面试题库15-题``
keeps a dash the convention would drop). Those links are normalised in the
source instead of being special-cased here.
"""
from __future__ import annotations

import re
import unicodedata

# Full-width / CJK punctuation -> deleted outright (no separator).
# Covers ：（）【】「」《》、。，；！？·…—～＋ etc.
_CJK_PUNCT = re.compile(
    r"[\u3000-\u303f\uFF00-\uFF65\uFFE0-\uFFEF"
    r"\u2018\u2019\u201c\u201d\u2026\u2014\u2013\u00b7]"
)
# Everything else that is not a word char or hyphen -> separator.
_SEP = re.compile(r"[^\w\-]+", re.UNICODE)
_DASH_RUN = re.compile(r"-{2,}")


def slugify(value: str, separator: str = "-") -> str:
    """Return a stable, CJK-preserving anchor id (GitHub convention)."""
    # NFC, not NFKC: full-width punctuation must stay full-width so the
    # delete rule above catches it instead of being folded to ASCII first.
    text = unicodedata.normalize("NFC", value or "").strip().casefold()
    text = _CJK_PUNCT.sub("", text)
    text = _SEP.sub(separator, text)
    text = _DASH_RUN.sub(separator, text)
    return text.strip(separator)
